--------------------------------------------------------
--  File created - Sunday-March-26-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPUSER
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."APPUSER" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"IS_ADMIN" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLASSROOMS
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."CLASSROOMS" 
   (	"ID" NUMBER(*,0), 
	"BUILDING" VARCHAR2(20 BYTE), 
	"CLASSROOM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."COURSE" 
   (	"CID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"DEPARTMENT" VARCHAR2(20 BYTE), 
	"CREDIT" NUMBER(*,0), 
	"COURSE_LEVEL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENROLLMENTS
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."ENROLLMENTS" 
   (	"STUDENT_ID" NUMBER, 
	"GPA" NUMBER(*,0), 
	"SCHED_ID" NUMBER, 
	"CLASSROOM_ID" NUMBER, 
	"CID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACULTY
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."FACULTY" 
   (	"FID" NUMBER(*,0), 
	"DEPARTMENT" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACULTY_GROUP
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."FACULTY_GROUP" 
   (	"COURSE_ID" NUMBER(*,0), 
	"SCHED_ID" NUMBER(*,0), 
	"CLASSROOM_ID" NUMBER(*,0), 
	"FID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OFFERINGS
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."OFFERINGS" 
   (	"CID" NUMBER(*,0), 
	"SCHED_ID" NUMBER(*,0), 
	"CLASSROOM_ID" NUMBER(*,0), 
	"MAX" NUMBER(*,0), 
	"WAITLIST" NUMBER(*,0), 
	"REMAINING" NUMBER(*,0), 
	"SEM" VARCHAR2(20 BYTE), 
	"YEAR" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRECON
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."PRECON" 
   (	"TAG" NUMBER(*,0), 
	"DESCRIPTION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRECONREQ
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."PRECONREQ" 
   (	"CID" NUMBER(*,0), 
	"TAG" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREREQ
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."PREREQ" 
   (	"CID" NUMBER(*,0), 
	"REQ_CID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCHEDULE
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."SCHEDULE" 
   (	"SID" NUMBER(*,0), 
	"MON" NUMBER(1,0), 
	"TUE" NUMBER(1,0), 
	"WED" NUMBER(1,0), 
	"THU" NUMBER(1,0), 
	"FRI" NUMBER(1,0), 
	"START_HOUR" NUMBER(2,0), 
	"START_MIN" NUMBER(2,0), 
	"END_HOUR" NUMBER(2,0), 
	"END_MIN" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPECIAL_REQ
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."SPECIAL_REQ" 
   (	"STUDENT_ID" NUMBER, 
	"GPA" NUMBER(*,0), 
	"SCHED_ID" NUMBER, 
	"CLASSROOM_ID" NUMBER, 
	"CID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "RMUDDUR"."STUDENT" 
   (	"STUDENT_ID" NUMBER, 
	"L_NAME" VARCHAR2(20 BYTE), 
	"DEPARTMENT" VARCHAR2(20 BYTE), 
	"GPA" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"F_NAME" VARCHAR2(20 BYTE), 
	"BILL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into RMUDDUR.APPUSER
SET DEFINE OFF;
Insert into RMUDDUR.APPUSER (USERNAME,PASSWORD,IS_ADMIN) values ('EVE','SIMPLE',0);
REM INSERTING into RMUDDUR.CLASSROOMS
SET DEFINE OFF;
REM INSERTING into RMUDDUR.COURSE
SET DEFINE OFF;
REM INSERTING into RMUDDUR.ENROLLMENTS
SET DEFINE OFF;
REM INSERTING into RMUDDUR.FACULTY
SET DEFINE OFF;
REM INSERTING into RMUDDUR.FACULTY_GROUP
SET DEFINE OFF;
REM INSERTING into RMUDDUR.OFFERINGS
SET DEFINE OFF;
REM INSERTING into RMUDDUR.PRECON
SET DEFINE OFF;
REM INSERTING into RMUDDUR.PRECONREQ
SET DEFINE OFF;
REM INSERTING into RMUDDUR.PREREQ
SET DEFINE OFF;
REM INSERTING into RMUDDUR.SCHEDULE
SET DEFINE OFF;
REM INSERTING into RMUDDUR.SPECIAL_REQ
SET DEFINE OFF;
REM INSERTING into RMUDDUR.STUDENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FACULTY_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."FACULTY_GROUP_PK" ON "RMUDDUR"."FACULTY_GROUP" ("COURSE_ID", "SCHED_ID", "CLASSROOM_ID", "FID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."UNAME_PK" ON "RMUDDUR"."APPUSER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OFFERINGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."OFFERINGS_PK" ON "RMUDDUR"."OFFERINGS" ("CLASSROOM_ID", "SCHED_ID", "CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."STUDENT_PK" ON "RMUDDUR"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRECONREQ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."PRECONREQ_PK" ON "RMUDDUR"."PRECONREQ" ("CID", "TAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACULTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."FACULTY_PK" ON "RMUDDUR"."FACULTY" ("FID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PREREQ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."PREREQ_PK" ON "RMUDDUR"."PREREQ" ("CID", "REQ_CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SCHEDULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."SCHEDULE_PK" ON "RMUDDUR"."SCHEDULE" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRECON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."PRECON_PK" ON "RMUDDUR"."PRECON" ("TAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLASSROOMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."CLASSROOMS_PK" ON "RMUDDUR"."CLASSROOMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."COURSE_PK" ON "RMUDDUR"."COURSE" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENROLLMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RMUDDUR"."ENROLLMENTS_PK" ON "RMUDDUR"."ENROLLMENTS" ("STUDENT_ID", "SCHED_ID", "CLASSROOM_ID", "CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OFFERINGS
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."OFFERINGS" ADD CONSTRAINT "OFFERINGS_PK" PRIMARY KEY ("CLASSROOM_ID", "SCHED_ID", "CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."OFFERINGS" MODIFY ("CID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."OFFERINGS" MODIFY ("SCHED_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."OFFERINGS" MODIFY ("CLASSROOM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRECON
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."PRECON" ADD CONSTRAINT "PRECON_PK" PRIMARY KEY ("TAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."PRECON" MODIFY ("TAG" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."PRECON" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACULTY_GROUP
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."FACULTY_GROUP" ADD CONSTRAINT "FACULTY_GROUP_PK" PRIMARY KEY ("COURSE_ID", "SCHED_ID", "CLASSROOM_ID", "FID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."FACULTY_GROUP" MODIFY ("COURSE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."FACULTY_GROUP" MODIFY ("SCHED_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."FACULTY_GROUP" MODIFY ("CLASSROOM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."FACULTY_GROUP" MODIFY ("FID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."STUDENT" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."COURSE" MODIFY ("CID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."COURSE" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPUSER
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."APPUSER" ADD CONSTRAINT "UNAME_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREREQ
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."PREREQ" ADD CONSTRAINT "PREREQ_PK" PRIMARY KEY ("CID", "REQ_CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."PREREQ" MODIFY ("CID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."PREREQ" MODIFY ("REQ_CID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."SCHEDULE" ADD CONSTRAINT "SCHEDULE_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("SID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("MON" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("TUE" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("WED" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("THU" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("FRI" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("START_HOUR" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("START_MIN" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("END_HOUR" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SCHEDULE" MODIFY ("END_MIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENROLLMENTS
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."ENROLLMENTS" ADD CONSTRAINT "ENROLLMENTS_PK" PRIMARY KEY ("STUDENT_ID", "SCHED_ID", "CLASSROOM_ID", "CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."ENROLLMENTS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."ENROLLMENTS" MODIFY ("SCHED_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."ENROLLMENTS" MODIFY ("CLASSROOM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."ENROLLMENTS" MODIFY ("CID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACULTY
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."FACULTY" ADD CONSTRAINT "FACULTY_PK" PRIMARY KEY ("FID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."FACULTY" MODIFY ("FID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLASSROOMS
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."CLASSROOMS" ADD CONSTRAINT "CLASSROOMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."CLASSROOMS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."CLASSROOMS" MODIFY ("CLASSROOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRECONREQ
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."PRECONREQ" ADD CONSTRAINT "PRECONREQ_PK" PRIMARY KEY ("CID", "TAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "RMUDDUR"."PRECONREQ" MODIFY ("CID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."PRECONREQ" MODIFY ("TAG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECIAL_REQ
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."SPECIAL_REQ" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SPECIAL_REQ" MODIFY ("SCHED_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SPECIAL_REQ" MODIFY ("CLASSROOM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "RMUDDUR"."SPECIAL_REQ" MODIFY ("CID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ENROLLMENTS
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."ENROLLMENTS" ADD CONSTRAINT "CLASSROOM_ENROLL" FOREIGN KEY ("CLASSROOM_ID")
	  REFERENCES "RMUDDUR"."CLASSROOMS" ("ID") ENABLE;
 
  ALTER TABLE "RMUDDUR"."ENROLLMENTS" ADD CONSTRAINT "ENROLL_COURSE" FOREIGN KEY ("CID")
	  REFERENCES "RMUDDUR"."COURSE" ("CID") ENABLE;
 
  ALTER TABLE "RMUDDUR"."ENROLLMENTS" ADD CONSTRAINT "SCHED_ENROLL" FOREIGN KEY ("SCHED_ID")
	  REFERENCES "RMUDDUR"."SCHEDULE" ("SID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACULTY_GROUP
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."FACULTY_GROUP" ADD CONSTRAINT "CLASSROOM" FOREIGN KEY ("CLASSROOM_ID")
	  REFERENCES "RMUDDUR"."CLASSROOMS" ("ID") ENABLE;
 
  ALTER TABLE "RMUDDUR"."FACULTY_GROUP" ADD CONSTRAINT "COURSE" FOREIGN KEY ("COURSE_ID")
	  REFERENCES "RMUDDUR"."COURSE" ("CID") ENABLE;
 
  ALTER TABLE "RMUDDUR"."FACULTY_GROUP" ADD CONSTRAINT "FACULTY" FOREIGN KEY ("FID")
	  REFERENCES "RMUDDUR"."FACULTY" ("FID") ENABLE;
 
  ALTER TABLE "RMUDDUR"."FACULTY_GROUP" ADD CONSTRAINT "SCHED_ID_FOREIGHKEY_SCHEDULE" FOREIGN KEY ("SCHED_ID")
	  REFERENCES "RMUDDUR"."SCHEDULE" ("SID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFFERINGS
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."OFFERINGS" ADD CONSTRAINT "CLASSROOM_OFFERING" FOREIGN KEY ("CLASSROOM_ID")
	  REFERENCES "RMUDDUR"."CLASSROOMS" ("ID") ENABLE;
 
  ALTER TABLE "RMUDDUR"."OFFERINGS" ADD CONSTRAINT "COURSE_OFFERING" FOREIGN KEY ("CID")
	  REFERENCES "RMUDDUR"."COURSE" ("CID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRECONREQ
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."PRECONREQ" ADD CONSTRAINT "PRECONREQ_FOREIGNKEY_COURSE" FOREIGN KEY ("CID")
	  REFERENCES "RMUDDUR"."COURSE" ("CID") ENABLE;
 
  ALTER TABLE "RMUDDUR"."PRECONREQ" ADD CONSTRAINT "PRECONREQ_FOREIGNKEY_PRECON" FOREIGN KEY ("TAG")
	  REFERENCES "RMUDDUR"."PRECON" ("TAG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREREQ
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."PREREQ" ADD CONSTRAINT "CID_FOREIGNKEY_COURSE" FOREIGN KEY ("CID")
	  REFERENCES "RMUDDUR"."COURSE" ("CID") ENABLE;
 
  ALTER TABLE "RMUDDUR"."PREREQ" ADD CONSTRAINT "REQ_CID_FOREIGNKEY_COURSE" FOREIGN KEY ("REQ_CID")
	  REFERENCES "RMUDDUR"."COURSE" ("CID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "RMUDDUR"."STUDENT" ADD CONSTRAINT "USERNAME_STUDENT" FOREIGN KEY ("USERNAME")
	  REFERENCES "RMUDDUR"."APPUSER" ("USERNAME") ENABLE;
